# Generated by Django 4.0.4 on 2022-05-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapstatistics',
            name='file',
            field=models.FileField(null=True, upload_to='map/', verbose_name=''),
        ),
    ]
