# Generated by Django 4.0.4 on 2022-05-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_mapstatistics_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapstatistics',
            options={'ordering': ['-id']},
        ),
    ]
