# Generated by Django 4.0.4 on 2022-06-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_mapstatistics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapstatistics',
            name='file',
            field=models.FileField(null=True, upload_to='map/', verbose_name='Faylni yuklang'),
        ),
        migrations.AlterField(
            model_name='mapstatistics',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nomi'),
        ),
    ]
