# Generated by Django 4.0.4 on 2022-07-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_alter_mapstatistics_file_alter_mapstatistics_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapstatistics',
            name='file',
            field=models.FileField(null=True, upload_to='map/'),
        ),
    ]
